---
driver:
  name: proxy
  host: &name 127.0.0.1
  username: &us root
  # port config in platform section
  ssh_key: &ck cluster-key

provisioner:
  name: ansible_playbook
  hosts: *name
  require_chef_for_busser: false
  ansible_verbose: false
  require_ansible_repo: true
  update_package_repos: false
  roles_path: roles
  ansible_connection: ssh  

verifier: 
  name: inspec

platforms:
  - name: &plt1 ubuntu%d
    image: &img1 weaveworks/ignite-ubuntu:20.04
    provisioner:
      name: ansible_playbook
      playbook: playbook.yaml
      ansible_version: 2.9.6+dfsg-1
    driver_config:
      port: &hp1 32700
      
  - name: &plt2 centos%d
    image: &img2 weaveworks/ignite-centos:7
    provisioner:
      name: ansible_playbook
      playbook: playbook.yaml
      ansible_version:  2.9.6
      ansible_binary_path: /usr/local/bin/ #RHEL/Centos Specific
      require_pip3: true #RHEL/Centos Specific
      ansible_package_name: ansible #RHEL/Centos Specific
    driver_config:
      port: &hp2 32701

transport:
  ssh_key: *ck 
  username: *us
  max_ssh_sessions: 1 # seems to be a bug whereby multiple ssh sessions can confuse/break runs

suites:
  - name: os-hardening
    run_list:
    attributes:
    verifier:
      inspec_tests:
        - name: os-hardening
          url: https://github.com/dev-sec/linux-baseline

lifecycle:
  pre_create:
  - local: |
      if [[ `uname` == "Darwin" ]]; then export IGNCMD=footloose; else export IGNCMD=ignite; fi; echo $IGNCMD > cmd.txt 
      command -v $(cat cmd.txt) >/dev/null 2>&1 || { echo >&2 "footloose/ignite is not installed. for install instructions see https://github.com/weaveworks/footloose#install"; exit 1; }
      $(cat cmd.txt) create --config kitchen.yml
  pre_destroy: 
  - local:  |
      if [[ `uname` == "Darwin" ]]; then export IGNCMD=footloose; else export IGNCMD=ignite; fi; echo $IGNCMD > cmd.txt 
      $(cat cmd.txt) delete --config kitchen.yml


############# FOOTLOOSE CONFIG ###################

cluster: 
  name: footloose
  privateKey: *ck 
machines:
- count: 1
  spec:
    image: *img1
    name: *plt1
    portMappings:
    - containerPort: 22
      hostport: *hp1 
- count: 1
  spec:
    image: *img2
    name: *plt2
    portMappings:
    - containerPort: 22
      hostport: *hp2 

############# FOOTLOOSE CONFIG END ###############
